stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-11
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-ebsconet:thunderjet-latest
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-n6zpg:thunderjet-helmcharts-mod-orders-storage
      version: 0.1.1
      answers:
        image.repository: docker.dev.folio.org/mod-ebsconet
        image.tag: thunderjet-latest
        postJob.enabled: "true"
      name: mod-ebsconet
      targetNamespace: thunderjet
timeout: 60
notification: {}
