spring:
  application:
    name: mod-ebsconet
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

feign:
  client:
    config:
      change-manager:
        logger-level: full
