server:
  port: 8081

spring:
  application:
    name: mod-ebsconet
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  jackson:
    default-property-inclusion: non_null

feign:
  client:
    config:
      change-manager:
        logger-level: full

management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace